on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  run:
    name: Run
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Update package.json
        run: npm version ${{vars.BUILD_VERSION}} --no-git-tag-version
      - name: Update microsoft-identity-association.json
        shell: pwsh
        run: |
          $content = Get-Content -Path ${{env.FILE_PATH}}
          $content = $content -replace "{{APP_CLIENT_ID}}", "${{vars.APP_CLIENT_ID}}"
          Out-File -FilePath ${{env.FILE_PATH}} -InputObject $content -Encoding UTF8
        env:
          FILE_PATH: public/.well-known/microsoft-identity-association.json
      - name: Update .env
        shell: pwsh
        run: |
          $content = Get-Content -Path ${{env.FILE_PATH}}
          $content = $content -Replace "{{TELEMETRY_CONNECTION_STRING}}", "${{vars.TELEMETRY_CONNECTION_STRING}}"
          $content = $content -Replace "{{APP_TENANT_ID}}", "${{vars.APP_TENANT_ID}}"
          $content = $content -Replace "{{APP_CLIENT_ID}}", "${{vars.APP_CLIENT_ID}}"
          $content = $content -Replace "{{APP_DOMAIN_NAME}}", "${{vars.APP_DOMAIN_NAME}}"
          Out-File -FilePath ${{env.FILE_PATH}} -InputObject $content -Encoding UTF8
        env:
          FILE_PATH: .env
      - name: Restore source
        run: npm ci
      - name: Audit source
        run: npm audit --omit=dev
      - name: Build source
        run: npm run build
      - name: Test source
        run: npm run test:ci
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
      - name: Upload test results
        uses: enricomi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: test/*.xml
          check_name: Test results
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
          slug: karamem0/hitofude
