name: Deploy to Azure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      slot-name:
        required: false
        type: string

permissions: {}

jobs:
  run:
    name: Run
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Connect to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{vars.AZURE_WEB_APP_NAME}}
          slot-name: ${{inputs.slot-name}}
          package: build
