name: Deploy to GitHub Release

on:
  workflow_call: {}

permissions:
  contents: write

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
