on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: dev
  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: dev
