on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Rewrite .env
        shell: pwsh
        run: |
          $content = Get-Content -Path .env
          $content = $content -replace "{{APPLICATIONINSIGHTS_INSTRUMENTATION_KEY}}", "${{secrets.APPLICATIONINSIGHTS_INSTRUMENTATION_KEY}}"
          $content = $content -replace "{{MSAL_AUTHORITY}}", "${{secrets.MSAL_AUTHORITY}}"
          $content = $content -replace "{{MSAL_CLIENT_ID}}", "${{secrets.MSAL_CLIENT_ID}}"
          Out-File -FilePath .env -InputObject $content -Encoding UTF8
      - name: Build source
        run: |
          npm ci
          npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: hitofude
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: hitofude
          path: artifact
      - name: Connect to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name ${{secrets.AZURE_STORAGE_ACCOUNT_NAME}} --source '$web'
            az storage blob upload-batch --account-name ${{secrets.AZURE_STORAGE_ACCOUNT_NAME}} --auth-mode key --destination '$web' --source artifact
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths '/*' --profile-name ${{secrets.AZURE_CDN_PROFILE_NAME}} --name ${{secrets.AZURE_CDN_ENDPOINT_NAME}} --resource-group ${{secrets.AZURE_RESOURCE_GROUP_NAME}}
