on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: prd
  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: prd
