on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*.*.*

jobs:
  deploy-development:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/workflow.deploy.yml
    secrets:
      APP_CLIENT_ID: ${{secrets.APP_CLIENT_ID}}
      APP_DOMAIN_NAME: ${{secrets.APP_DOMAIN_NAME}}
      APP_TENANT_ID: ${{secrets.APP_TENANT_ID}}
      AZURE_CDN_ENDPOINT_NAME: ${{secrets.AZURE_CDN_ENDPOINT_NAME}}
      AZURE_CDN_PROFILE_NAME: ${{secrets.AZURE_CDN_PROFILE_NAME}}
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
      AZURE_RESOURCE_GROUP_NAME: ${{secrets.AZURE_RESOURCE_GROUP_NAME}}
      AZURE_STORAGE_ACCOUNT_NAME: ${{secrets.AZURE_STORAGE_ACCOUNT_NAME}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      TELEMETRY_CONNECTION_STRING: ${{secrets.TELEMETRY_CONNECTION_STRING}}
    with:
      environment: development
  deploy-production:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/workflow.deploy.yml
    secrets:
      APP_CLIENT_ID: ${{secrets.APP_CLIENT_ID}}
      APP_DOMAIN_NAME: ${{secrets.APP_DOMAIN_NAME}}
      APP_TENANT_ID: ${{secrets.APP_TENANT_ID}}
      AZURE_CDN_ENDPOINT_NAME: ${{secrets.AZURE_CDN_ENDPOINT_NAME}}
      AZURE_CDN_PROFILE_NAME: ${{secrets.AZURE_CDN_PROFILE_NAME}}
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
      AZURE_RESOURCE_GROUP_NAME: ${{secrets.AZURE_RESOURCE_GROUP_NAME}}
      AZURE_STORAGE_ACCOUNT_NAME: ${{secrets.AZURE_STORAGE_ACCOUNT_NAME}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      TELEMETRY_CONNECTION_STRING: ${{secrets.TELEMETRY_CONNECTION_STRING}}
    with:
      environment: production
  create-release:
    if: contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/workflow.release.yml
    with:
      environment: production
